version: '3.8'

services:
  backend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: aws-sns-sample
    volumes:
      - '.:/go/app'
    ports:
      - '9015:9015'
    tty: true
    stdin_open: true
